---

- name: Install required support libraries
  apt: name="{{ item }}" state=present
  with_items:
    - libgtk2.0-0
    - libgtk2.0-bin
    - libgtk2.0-dev

- name: Install required binaries
  apt: name="{{ item }}" state=present
  with_items:
    - git
